language: node_js

node_js:
  - '8'
  - '7'
  - '6'
  - '4'

branches:
  only:
    - master

cache: yarn

script: yarn run check

after_success:
  - yarn global add coveralls travis-deploy-once
  - cat ./coverage/lcov.info | coveralls
  - travis-deploy-once "yarn global add semantic-release@12 && semantic-release"
